---

- fail: msg="DEPLOY_DRIVER must be specified"
  when: DEPLOY_DRIVER is not defined

- fail: msg="unsupported DEPLOY_DRIVER"
  when: DEPLOY_DRIVER not in ['git']

####################################################

# remote pre-deploy
- include: deploy-predeploy.yml
  tags:
    - deploy-only

# remote deploy (using driver)
- include: git-deploy.yml
  tags:
    - deploy-only
#  when: DEPLOY_DRIVER is 'git'

# remote post-deploy
- include: deploy-postdeploy.yml
  tags:
    - deploy-only
