---

- name: ensure proper permissions
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ HTTPD_USER }}"
    state: directory
    mode: 0770
  sudo: True
  with_items:
    - "{{ MAGE_ROOT }}/var"
  #  - "{{ MAGE_ROOT }}/media"
    - "{{ MAGE_ROOT }}/includes"
  ignore_errors: yes


- name: ensure shared directory links
  file:
    path: "{{ MAGE_ROOT }}/{{ item }}"
    src: "/nfs/{{ SUBDOMAIN }}.{{ DOMAIN }}/{{ item }}"
    state: link
  sudo: True
  with_items:
    - "media"
    - "var/export"
    - "var/powerreviews"
    - "var/storelocator"
    - "var/trackingimport"
    - "var/urapidflow"
  ignore_errors: yes


- name: ensure environment configuration + webroot defaults
  shell: ./env.sh sync --no-prompt
  args:
    chdir: "{{ REPO_ROOT }}"
  ignore_errors: yes
