---

# @TODO/@DEPRECATE - remove once skels have been updated.
- fail: msg="including git-deploy.yml directly is deprecated. please update your playbook to include deploy.yml passing the git DEPLOY_DRIVER. see example in {{ LOCAL_ROOT }}/skel/boilerplate/ansible/deploy.yml"
  when: DEPLOY_DRIVER is not defined

# pre-deployment
################
- include: git-deps.yml
- include: git-predeploy.yml

# remote-deployment
###################

#- include: notify-hipchat.yml
#  vars:
#    HIPCHAT_MESSAGE: "{{ CLIENT_CODE }}-{{  ENV }} deployment started by {{ lookup('pipe', 'whoami') }}@{{ lookup('pipe', 'hostname') }} for , ref: {{ REPO_REF }}, skel: {{ SKEL_VERSION | default('unknown version') }}"

- name: git checkout
  git:
    repo: "{{ REPO_REMOTE }}"
    version: "{{ REPO_REF }}"
    dest: "{{ REPO_ROOT }}"
    key_file: "{{ BLUEACORN_DIR }}/util/github-deploy.key"
    force: yes
    accept_hostkey: yes

# post-deployment
#################

- include: git-postdeploy.yml
