---

- name: make sure we compile assets from the REPO_REF being deployed
  local_action: shell echo "currently on $(git rev-parse --abbrev-ref HEAD) , deploying {{ REPO_REF }}" ; [ "$(git rev-parse HEAD)" = "$(git rev-parse {{ REPO_REMOTE_NAME | default('origin') }}/{{ REPO_REF }})" ] || exit 1
  args:
    chdir: "{{ LOCAL_ROOT }}/"
  run_once: True
  tags:
    - grunt
    - grunt-compile-only

# @TODO better way to handle deps quickly?
- name: ensure deps [ npm install ; bower install ] if node_module !exists
  local_action: shell npm install --production ; bower --allow-root --config.interactive=false install
  args:
    creates: "{{ LOCAL_ROOT }}/blueacornui/node_modules"
    chdir: "{{ LOCAL_ROOT }}/blueacornui"
  run_once: True
  tags:
    - grunt
    - grunt-compile-only


- name: prepare / compile static assets
  local_action: shell grunt {{ GRUNT_COMMAND | default('production') }}
  args:
    chdir: "{{ LOCAL_ROOT }}/blueacornui"
  run_once: True
  tags:
    - grunt
    - grunt-compile-only
