---

- debug: msg="indexer set to {{ INDEXER }}"

- name: reindex indexer(s)
  shell: php shell/indexer.php --reindex {{ INDEXER }}
  args:
    chdir: "{{ APP_ROOT }}"
  become: True
  become_user: "{{ HTTPD_USER }}"
  tags:
    - reindex
