---
  
- name: set hostname
  hostname: name={{ PREFERED_HOSTNAME | default(inventory_hostname) }}
  become: True
  tags:
    - provision
    - provision-hostname-only

- name: ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ PREFERED_HOSTNAME | default(inventory_hostname) }}"
  become: True
  tags:
    - provision
    - provision-hostname-only
