---

# local pre-deploy steps
########################
- name: "term-container local pre-deployment"
  hosts: term-container
  gather_facts: False
  tasks:

    - name: fail to deploy on local environments
      fail: msg="not supported on local environments"
      when: DOCKER_MACHINE == 'local'

    - name: start local pre-deployment tasks
      include: tasks/deploy/local/pre.yml

# remote pre-deploy steps
########################
- name: "term-container remote pre-deployment"
  hosts: term-container
  gather_facts: False
  any_errors_fatal: yes
  tasks:
    - name: start remote pre-deployment tasks
      include: tasks/deploy/remote/pre.yml

# remote deployment
###################
- name: "term-container remote deployment"
  hosts: term-container
  gather_facts: False
  any_errors_fatal: yes
  tasks:
    - name: start remote [git] deployment tasks
      include: tasks/deploy/git/deploy.yml
      vars:
        SKIP_DEPS: True

    # no blueacornui? set SKIP_BLUEACORNUI in appvars, group_vars, or envars
    # multiple blueacornui dirs? adjust with_items
    - name: start local build tasks (blueacornui compilation)
      include: "tasks/build/blueacornui-compile.yml"
      vars:
        SKIP_BUILD_CHECKS: True
        FORCE_BUILD_PATH: "{{ REPO_ROOT }}"
      with_items:
        - blueacornui
      when: SKIP_BLUEACORNUI is not defined or not SKIP_BLUEACORNUI

# remote post-deploy steps
##########################
- name: "term-container remote post-deployment"
  hosts: term-container
  gather_facts: False
  any_errors_fatal: yes
  tasks:

    - name: start remote post-deployment tasks
      include: tasks/deploy/remote/post.yml

    # @TODO use UFS mount or dumbnail module. for now, copy media
    # @TODO if copying media, lets use rsync
    - name: copy media from NFS
      shell: cp -dR /nfs/snapshots/clients/{{ CLIENT_CODE }}/{{ SNAPSHOT_BASE_ENV }}/media {{ APP_ROOT }}/
      args:
        creates: "{{ APP_ROOT }}/media/catalog"
      tags:
        - filesystem

# run filesystem playbook to fix perms + setup NFS filesharing
##############################################################
- include: dockerized.util-filesystem.yml

# run cacheclear playbook after deployment
##########################################
- include: dockerized.util-cacheclear.yml

# local post-deploy steps
########################
- name: "term-container local post deployment"
  hosts: 127.0.0.1
  
  gather_facts: False
  tasks:
    - include: tasks/deploy/local/post.yml
