---

#
# best to avoid customizations on these while we iron it out.
#

- name: "term-container - qa environment deployment"
  hosts: term-container
  any_errors_fatal: yes
  vars:
    HTTPD_USER: www-data
  tasks:

    - name: git checkout
      git:
        repo: "{{ REPO_REMOTE }}"
        version: "{{ REPO_REF }}"
        dest: "{{ REPO_ROOT }}"
        force: yes
        accept_hostkey: yes
      tags:
        - git

    # @TODO use UFS mount or dumbnail module. for now, copy media
    - name: copy media from NFS
      shell: cp -dR /nfs/snapshots/clients/{{ CLIENT_CODE }}/{{ SNAPSHOT_BASE_ENV }}/media {{ APP_ROOT }}/media
      args:
        creates: "{{ APP_ROOT }}/media/catalog"
      notify: fix media permissions
      tags:
        - filesystem

    # ensure HTTPD_USER writable paths
    - include: tasks/fs-perms.yml
        WRITABLE_PATHS:
          - "{{ APP_ROOT }}/var"
          - "{{ APP_ROOT }}/media"
          - "{{ APP_ROOT }}/includes"
      notify:
        - fix media permissions
        - fix var permissions

    - include: tasks/deploy-postdeploy.yml

    - name: blueacornui / grunt dependencies
      shell: npm install --production ; bower --allow-root --config.interactive=false install
      args:
        chdir: "{{ REPO_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
      tags:
        - grunt

    - name: blueacornui / grunt compilation
      shell: grunt {{ GRUNT_COMMAND | default('production') }}
      args:
        chdir: "{{ REPO_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
      tags:
        - grunt

  handlers:
    - name: fix media permissions
      shell: chown -R {{ HTTPD_USER }}.{{ HTTPD_USER }} * && find . -type d -exec chmod 0755 {} \; && find . -type f -exec chmod 0644 {} \;
      args:
        chdir: "{{ APP_ROOT }}/media"

    - name: fix var permissions
      shell: chown -R {{ HTTPD_USER }}.{{ HTTPD_USER }} * && find . -type d -exec chmod 0755 {} \; && find . -type f -exec chmod 0644 {} \;
      args:
        chdir: "{{ APP_ROOT }}/var"

# run cacheclear playbook after deployment
##########################################
- include: qa.util-cacheclear.yml
