---

#
# best to avoid customizations on these while we iron it out.
#

- name: "term-container - qa environment deployment"
  hosts: term-container
  any_errors_fatal: yes
  tasks:

    - name: git checkout
      git:
        repo: "{{ REPO_REMOTE }}"
        version: "{{ REPO_REF }}"
        dest: "{{ REPO_ROOT }}"
        force: yes
        accept_hostkey: yes
      tags:
        - git

    # @TODO use UFS mount or dumbnail module. for now, copy media
    - name: copy media from NFS
      shell: cp -dR /nfs/snapshots/clients/{{ CLIENT_CODE }}/{{ SNAPSHOT_BASE_ENV }}/media {{ APP_ROOT }}/media
      args:
        creates: "{{ APP_ROOT }}/media/catalog"
      notify: fix media permissions
      tags:
        - filesystem

    - name: ensure var/ exists and is writable
      file:
        path: "{{ APP_ROOT }}/var"
        state: directory
        mode: 0777

    - include: tasks/conf-envsync.yml

    - name: blueacornui / grunt dependencies
      shell: npm install --production ; bower --allow-root --config.interactive=false install
      args:
        chdir: "{{ REPO_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
      tags:
        - grunt

    - name: blueacornui / grunt compilation
      shell: grunt {{ GRUNT_COMMAND | default('production') }}
      args:
        chdir: "{{ REPO_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
      tags:
        - grunt

  handlers:
    - name: fix media permissions
      shell: chmod -R 777 {{ APP_ROOT }}/media

# run cacheclear playbook after deployment
##########################################
- include: qa.util-cacheclear.yml
