---

#
# deploy a codebase across all webnodes
#
# !! be sure to properly define writable paths/permissions and shared folders
#

- name: "@CLIENT_CODE:@ENV deployment"
  hosts: web*
  gather_facts: False
  any_errors_fatal: yes
  tasks:

    # grunt compile blueacornui (locally, on machine running ansible)
    - include: tasks/grunt-compile.yml
      vars:
        BLUEACORNUI_DIR: "blueacornui"

    # deployment tasks (updates remote hosts)
    #########################################
    - include: tasks/deploy.yml
      vars:
        DEPLOY_DRIVER: git

    # copy (rsync) grunt compiled assets (from ansible host => remote hosts)
    - include: tasks/grunt-sync.yml
      vars:
        THEME_DIR: "skin/frontend/blueacorn/mis"
        SYNCED_PATHS:
          - "css"
          - "jsmin"

  post_tasks:

    # ensure HTTPD_USER writable paths
    - include: tasks/fs-perms.yml
      vars:
        WRITABLE_PATHS:
          - "{{ APP_ROOT }}/var"
          - "{{ APP_ROOT }}/media"
          - "{{ APP_ROOT }}/includes"

    # setup shared/linked folders (e.g. NFS shares).
#    - include: tasks/fs-shares.yml
#      vars:
#        SHARE_ROOT: /nfs/{{ SUBDOMAIN }}.{{ DOMAIN }}
#        LINKED_PATHS:
#          - "media"
#          - "var/export"
#          - "var/import"
#          - "var/powerreviews"
#          - "var/urapidflow"

    # post deployment and notifications
    - include: tasks/postdeploy.yml


# run cacheclear playbook after deployment
##########################################
- include: staging.util-cacheclear.yml

# run reindex playbook if requested
###################################
# @TODO: ansible 2.0, conditionally include indexer playbook.
# for now, do not re-index on every deployment.
# - include: @ENV.util-indexer.yml
