---

- name: "MIS:staging deployment"
  hosts: web*
  gather_facts: False
  any_errors_fatal: yes

  pre_tasks:

    # compile assets
    - include: tasks/grunt.yml


  tasks:

    # deploy site
    - include: tasks/git-deploy.yml

    # sync compiled assets
    - name: sync assets compiled by grunt
      synchronize:
        src: "../../webroot/skin/frontend/blueacorn/{{ THEME }}/{{ item }}"
        dest: "{{ REPO_ROOT }}/webroot/skin/frontend/blueacorn/{{ THEME }}/{{ item }}"
        archive: no
        copy_links: yes
        delete: yes
        mode: push
        recursive: yes
      with_items:
        - css/
        - jsmin/
      tags:
        - deploy
        - assets

  post_tasks:

    # notify services
    #- include: tasks/notify-newrelic.yml
    # - include: tasks/notify-hipchat.yml


# clear cache
- include: staging.cacheclear.yml
