---

# cacheclear -- also called by deploy playbook.


#
# clear filesystem cache and merged css|js across all webnodes
#

- name: "@CLIENT_CODE:common clear merged JS and CSS"
  hosts: web*
  gather_facts: False
  tasks:
    - include: tasks/cache/filesystem.yml


#
# clears cache stored in redis
#
#  !! be sure "admin" host is part of your inventory / ssh_config,
#     and has redis-cli available.
#
#  !! double check that the database IDs and ports are correct,
#     typically these are in group_vars/<environment_name>.yml
#
# safely removed if not using redis|memcache
#

- name: "@CLIENT_CODE:common clear redis cache"
  hosts: ADMIN_HOST
  gather_facts: no
  tasks:
    - include: tasks/cache/redis.yml


# EXAMPLE:
# clear akamai cdn cache w/ purge request
#  - Requires httpdlib2 on ansible host
#

#- name: "@CLIENT_CODE:@ENV clear cdn caches"
#  hosts: 127.0.0.1
#  connection: local
#  gather_facts: no
#  tasks:
#    - include: tasks/cache/akamai.yml
#      vars:
#        AKAMAI_USER:
#        AKAMAI_PASS:
#        AKAMAI_BODY:
#          type: cpcode
#          objects:
#          - "410810"
