---

- name: install nfs-client deps
  apt:
    name: nfs-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  
- name: detect if NFS-SERVER
  stat: path="/mnt/nfs-export"
  register: nfs_export 
  
- name: ensure nfs directory [client]
  file:
    path: /nfs
    state: directory
  when: not nfs_export.stat.exists

- name: mount nfs
  mount: 
    name: /nfs
    src: lc-web-admin:/mnt/nfs-export
    fstype: nfs
    opts: defaults
    state: mounted
  when: not nfs_export.stat.exists
