---

# @TODO : Notify hipchat of database snapshot

- debug: msg="*** writing database to {{ BLUEACORN_DIR }}/tmp/{{ CLIENT_CODE }}-{{ ENV }}.database.sql.gz and copying to {{ SNAPSHOT_BASE }}/{{ CLIENT_CODE }}-{{ ENV }}.database.sql.gz ***"

- name: ensure database snapshot script
  copy:
    src: "files/ba-snapdb.sh"
    dest: "{{ BLUEACORN_DIR }}/util/ba-snapdb.sh"
    mode: 0755
  tags:
    - snapshot
    - snapshot-database-only

- name: remove existing database snapshot
  file:
    path: "{{ BLUEACORN_DIR }}/tmp/{{ CLIENT_CODE }}-{{ ENV }}.database.sql.gz"
    state: absent
  tags:
    - snapshot
    - snapshot-database-only

- name: perform database snapshot
  shell: "{{ BLUEACORN_DIR }}/util/ba-snapdb.sh --no-prompt \
    {{ BLUEACORN_DIR }}/tmp/{{ CLIENT_CODE }}-{{ ENV }}.database.sql.gz \
    -m {{ APP_ROOT }}/"
  run_once: True
  register: result
  tags:
    - snapshot
    - snapshot-database-only

- name: fetch database snapshot
  fetch:
    src: "{{ BLUEACORN_DIR }}/tmp/{{ CLIENT_CODE }}-{{ ENV }}.database.sql.gz"
    dest: "{{ SNAPSHOT_BASE }}/"
    flat: yes
    fail_on_missing: yes
  run_once: True
  tags:
    - snapshot
    - snapshot-database-only
