---

# @TODO : Notify hipchat of media snapshot
- debug: msg="*** syncing {{ MEDIA_DIR }} to {{ SNAPSHOT_BASE }}/media ***"
  tags:
    - snapshot
    - snapshot-media-only

- name: ensure media directory exists on remote host
  shell: "[ -d {{ MEDIA_DIR }} ] || exit -1"
  register: result
  failed_when: result.rc != 0
  changed_when: False
  tags:
    - snapshot
    - snapshot-media-only

- name: ensure local target directory
  local_action: shell [ -d {{ SNAPSHOT_BASE }}/media ] && exit 99 || \
    mkdir -p {{ SNAPSHOT_BASE }}/media && exit 100
  register: result
  failed_when: result.rc < 99
  changed_when: result.rc > 99
  run_once: True
  tags:
    - snapshot
    - snapshot-media-only

- name: sync media
  synchronize:
    mode: pull
    src: "{{ MEDIA_DIR }}/"
    dest: "{{ SNAPSHOT_BASE }}/media"
    copy_links: yes
    archive: no
    recursive: yes
    delete: yes
    rsync_opts:
      - "--cvs-exclude"
      - "--exclude .thumbs"
      - "--exclude catalog/category/cache"
      - "--exclude catalog/product/cache"
      - "--exclude tmp/"
      - "--exclude css/"
      - "--exclude js/"
      - "--exclude css_secure/"
      - "--exclude *.gz"
      - "--exclude *.tgz"
      - "--exclude *.zip"
      # exclude hidden dirs
      - "--exclude .*"
  run_once: True
  tags:
    - snapshot
    - snapshot-media-only

- name: compress media
  local_action: shell cd {{ SNAPSHOT_BASE }} && \
    tar czf {{ CLIENT_CODE }}-{{ ENV }}.media.tar.gz media/
  run_once: True
  when: AUTO_COMPRESS_MEDIA is defined and AUTO_COMPRESS_MEDIA
  tags:
    - snapshot
    - snapshot-media-only
