---

- name: start/toggle vanilla magento cron tasks
  include: magento.yml
  vars:
    ba_cron_toggle: "{{ (CRON_TYPE == 'magento') | ternary('present','absent') }}"

- name: start/toggle aoe cron tasks
  include: aoe.yml
  vars:
    ba_cron_toggle: "{{ (CRON_TYPE == 'aoe') | ternary('present','absent') }}"
