---

# local pre-deploy steps
########################
- name: "@CLIENT_CODE:@ENV local pre-deployment"
  hosts: localhost
  gather_facts: False
  tasks:

    - name: start local pre-deployment tasks
      include: tasks/deploy/local/pre.yml

    # no blueacornui? comment out! multiple blueacornui dirs? adjust with_items
    - name: start local build tasks (blueacornui compilation)
      include: "tasks/build/blueacornui-compile.yml"
      with_items:
        - blueacornui

# remote pre-deploy steps
########################
- name: "@CLIENT_CODE:@ENV remote pre-deployment"
  hosts: web*
  gather_facts: False
  any_errors_fatal: yes
  tasks:
    - name: start remote pre-deployment tasks
      include: tasks/deploy/remote/pre.yml

# remote deployment
###################
- name: "@CLIENT_CODE:@ENV remote deployment"
  hosts: web*
  gather_facts: False
  any_errors_fatal: yes
  tasks:
    - name: start remote [git] deployment tasks
      include: tasks/deploy/git/deploy.yml

# remote post-deploy steps
##########################
- name: "@CLIENT_CODE:@ENV remote post-deployment"
  hosts: web*
  gather_facts: False
  any_errors_fatal: yes
  tasks:

    # sync [blueacornui] build artifacts
    # no blueacornui? comment out! multiple blueacornui dirs? adjust with_items
    - name: start syncing build artifacts
      include: "tasks/build/sync.yml"
      vars:
        SYNCED_PATHS:
          - "css"
          - "jsmin"
      with_items:
        - "webroot/skin/frontend/blueacorn/site"

    - name: start remote post-deployment tasks
      include: tasks/deploy/remote/post.yml

# run filesystem playbook to fix perms + setup NFS filesharing
##############################################################
- include: @ENV.util-filesystem.yml

# run cacheclear playbook after deployment
##########################################
#- include: @ENV.util-cacheclear.yml
- include: util-cacheclear.yml

# local post-deploy steps
########################
- name: "@CLIENT_CODE:@ENV local post deployment"
  hosts: localhost
  gather_facts: False
  tasks:
    - include: tasks/deploy/local/post.yml
