---

# cleanup old redis tags
- name: ensure redis cleanup script
  template:
    src: templates/redis-cleanup.php
    dest: "{{ BLUEACORN_DIR }}/util/{{ ENV }}.redis-cleanup.php"
    mode: 0755
    
- name: schedule redis cleanup
  cron:
    job: "php {{ BLUEACORN_DIR }}/util/{{ ENV }}.redis-cleanup.php"
    hour: "*/8"
    name: "{{ ENV }} redis cleanup"
    user: "{{ HTTPD_USER }}"
    state: present
  sudo: True