---

- name: make sure we compile assets from the REPO_REF being deployed
  local_action: shell echo "currently on $(git rev-parse --abbrev-ref HEAD) , deploying {{ REPO_REF }}" ; [ "$(git rev-parse HEAD)" = "$(git rev-parse {{ REPO_REMOTE_NAME | default('origin') }}/{{ REPO_REF }})" ] || exit 1
  args:
    chdir: "{{ LOCAL_ROOT }}/"
  run_once: True
  when: SKIP_CHECKS is not defined or not SKIP_CHECKS
  tags:
    - grunt
    - grunt-compile-only



#
# npm deps
#

- name: fingerprint npm/package.json contents
  local_action: shell [ "$(shasum package.json | awk '{print $1}')" == "$(cat node_modules/fingerprint.sha)" ] || exit 99
  args:
    chdir: "{{ LOCAL_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
  run_once: True
  always_run: True
  ignore_errors: True
  register: fingerprint
  tags:
    - grunt
    - grunt-compile-only

- name: ensure npm/package.json deps
  local_action: shell npm install --production && echo $(shasum package.json | awk '{print $1}') > node_modules/fingerprint.sha
  args:
    chdir: "{{ LOCAL_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
  run_once: True
  when: fingerprint|failed
  tags:
    - grunt
    - grunt-compile-only



#
# bower deps
#


- name: fingerprint bower/bower.json contents
  local_action: shell [ "$(shasum bower.json | awk '{print $1}')" == "$(cat bower_components/fingerprint.sha)" ] || exit 99
  args:
    chdir: "{{ LOCAL_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
  run_once: True
  always_run: True
  ignore_errors: True
  register: fingerprint
  tags:
    - grunt
    - grunt-compile-only

- name: ensure bower/bower.json deps
  local_action: shell bower --allow-root --config.interactive=false install && echo $(shasum bower.json | awk '{print $1}') > bower_components/fingerprint.sha
  args:
    chdir: "{{ LOCAL_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
  run_once: True
  when: fingerprint|failed
  tags:
    - grunt
    - grunt-compile-only



#
# bombs away
#


- name: prepare / compile static assets
  local_action: shell grunt {{ GRUNT_COMMAND | default('production') }}
  args:
    chdir: "{{ LOCAL_ROOT }}/{{ BLUEACORNUI_DIR | default('blueacornui') }}"
  run_once: True
  tags:
    - grunt
    - grunt-compile-only
