---

- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

    
- name: copy site configuration
  template: 
    src: "{{ item }}"
    dest: "{{ BLUEACORN_DIR }}/conf/nginx-{{ ENV }}.conf"
  with_first_found:
    - "{{ inventory_hostname }}.{{ ENV }}.nginx.conf"
    - "{{ ENV }}.nginx.conf"
    - "nginx.conf"
  notify: restart nginx
  
    
- name: activate site configuration
  file:
    path: "/etc/nginx/sites-enabled/{{ DOMAIN }}-{{ ENV }}.conf"
    src: "{{ BLUEACORN_DIR }}/conf/nginx-{{ ENV }}.conf"
    force: yes
    state: link
  notify: restart nginx
  when: ansible_os_family == "Debian"