---

# on sudoless environments, copy task contents to deployment palybook

- name: ensure HTTPD_USER writable paths
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ HTTPD_USER }}"
    mode: 0770
    state: directory
  become: True
  with_items: WRITABLE_PATHS
  ignore_errors: yes
  tags:
    - filesystem
    - filesystem-perms-only
