---

#
#  setup scheduled tasks like magento's cron and redis cleanup scripts
#
#  !! to enable cron, add the "cron" host to your inventory / ssh_config
#     it typically points to the admin or web-1 node.
#

- name: "@CLIENT_CODE:common scheduled tasks"
  # do not change the "cron" host! if not in inventory, will skip this play
  hosts: CRON_HOST
  gather_facts: False
  tasks:

    # Schedule Magento Cron
    #   If using AOE, set CRON_TYPE to "aoe". Else use "magento" for vanilla
    #   CRON_TYPE is set in inventory / group_vars
    #   You may also change the CRON_INTERVAL. Defaults to every minute. E.g.
    #     CRON_INTERVAL: "*/5"  <-- to run every 5 minutes
    #
    #   NOTE: magento requres cron be run as HTTPD_USER - the below tasks
    #         use sudo (become: True) to register jobs in the HTTPD_USER's
    #         crontab. _THIS REQUIRES A WORKING SUDO_. If you do NOT have sudo
    #         access, ask the provider to register the jobs under HTTPD_USER,
    #         or if HTTPD_USER is the ssh user, then copy the contents of
    #         appropriate task and remove or set "become: False"...
    #
    #         ansible doesn't support a conditional become: value, and we want
    #         to avoid code replication while ensuring cron runs appropriately.
    #
    - include: tasks/cron/cron.yml


- name: "@CLIENT_CODE:common schedule redis cleanup"
  # do not change the "admin" host! if not in inventory, will skip this play
  hosts: ADMIN_HOST
  gather_facts: False
  tasks:
    - include: tasks/cache/redis.yml
      when: REDIS_HOST is defined and REDIS_HOST
