---

# remote pre-deployment tasks
##############################

- name: detect prior deployment
  stat: path="{{ REPO_ROOT }}"
  register: repo_root
  always_run: yes
  tags:
    - env-test

- name: test for on-server configuration changes
  shell: bin/env test
  args:
    chdir: "{{ REPO_ROOT }}"
  ignore_errors: yes
  register: result
  always_run: yes
  when: repo_root.stat.exists and (SKIP_FS_CHECK is not defined or not SKIP_FS_CHECK) and (SKIP_ALL_CHECKS is not defined or not SKIP_ALL_CHECKS)
  tags:
    - env-test

- name: fail if on server configuration changes were detected
  fail: msg="test failure typically occurs when configuration files are edited on the server. be sure to track these changes in the skel branch and re-deploy. pass SKIP_FS_CHECK=true as an extravar to skip."
  when: repo_root.stat.exists and (SKIP_FS_CHECK is not defined or not SKIP_FS_CHECK) and (SKIP_ALL_CHECKS is not defined or not SKIP_ALL_CHECKS) and result.rc > 0 and result.rc < 100
  tags:
    - env-test


# include application remote pre-deployment
- name: start remote [application-specific] pre-deployment tasks
  include: app/pre.yml
