---

#
# variables matching a particular environment.
#  ^^^ Replace this with environment name. @TODO automate this
#

################################################################################
# HTTPD_USER - for ownership. use php-fpm user, or webserver user if modphp
HTTPD_USER: www-data


################################################################################
# REDIS_HOST - IP/Hostname of Redis Server. Leave non-truthy if not using redis.
#REDIS_HOST: 172.16.0.77
REDIS_FPC_PORT: 6382
REDIS_FPC_DB: 0
REDIS_OBJ_PORT: 6381
REDIS_OBJ_DB: 0


################################################################################
# playbook behavior configurations, generally safe to leave as-is

# GRUNT_COMMAND: - passed to blueacornui compile job. defaults to 'production'
# GRUNT_COMMAND: compile

# NEWRELIC_APPID: - APM name to notify on deployments
#   leave blank to skip
NEWRELIC_APPID:
