---

#
# variables matching a particular environment.
#  ^^^ Replace this with environment name. @TODO automate this
#

################################################################################
# HTTPD_USER - for ownership. use php-fpm user, or webserver user if modphp
HTTPD_USER: missionrs


################################################################################
# REDIS_CACHES: definition of redis caches to clear. define an empty dict if
#               not using redis.
# REDIS_CACHES: {}
REDIS_CACHES:
   default:
     host: 172.24.16.35
     port: 6379
     db: 0
     cmd: flushdb

   fpc:
     host: 172.24.16.35
     port: 6379
     db: 1
     cmd: flushdb

   obj:
     host: 172.24.16.35
     port: 6379
     db: 0
     cmd: flushdb

################################################################################
# playbook behavior configurations, generally safe to leave as-is

# GRUNT_COMMAND: - passed to blueacornui compile job. defaults to 'production'
# GRUNT_COMMAND: compile

# NEWRELIC_APPID: - APM name to notify on deployments
#   leave blank to skip
NEWRELIC_APPID: